/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alex_kotlin_myjni_BsdiffUtils */

#ifndef _Included_com_alex_kotlin_myjni_BsdiffUtils
#define _Included_com_alex_kotlin_myjni_BsdiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alex_kotlin_myjni_BsdiffUtils
 * Method:    diffApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alex_kotlin_myjni_BsdiffUtils_diffApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_alex_kotlin_myjni_BsdiffUtils
 * Method:    diffApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_alex_kotlin_myjni_BsdiffUtils_combineNewApk
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_alex_kotlin_myjni_BsdiffUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_alex_kotlin_myjni_BsdiffUtils_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
